"""initial

Revision ID: 0c9e75f03065
Revises: 
Create Date: 2019-05-18 19:45:03.915227

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0c9e75f03065'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_media',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'media_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('migrate_version')
    op.add_column('tweet', sa.Column('media_url', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'tweet_media', ['media_url'], ['id'])
    op.drop_column('tweet', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('image_url', sa.TEXT(),
                                     autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'media_url')
    op.create_table('migrate_version',
                    sa.Column('repository_id', sa.VARCHAR(length=250),
                              autoincrement=False, nullable=False),
                    sa.Column('repository_path', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('version', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'repository_id', name='migrate_version_pkey')
                    )
    op.drop_table('tweet_media')
    # ### end Alembic commands ###
