"""initial

Revision ID: b3b9daaf1741
Revises: 0c9e75f03065
Create Date: 2019-05-18 19:54:42.592972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b9daaf1741'
down_revision = '0c9e75f03065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('media_id', sa.Integer(), nullable=True))
    op.drop_constraint('tweet_media_url_fkey', 'tweet', type_='foreignkey')
    op.create_foreign_key(None, 'tweet', 'tweet_media', ['media_id'], ['id'])
    op.drop_column('tweet', 'media_url')
    op.add_column('tweet_media', sa.Column('tweet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweet_media', 'tweet', ['tweet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet_media', type_='foreignkey')
    op.drop_column('tweet_media', 'tweet_id')
    op.add_column('tweet', sa.Column('media_url', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.create_foreign_key('tweet_media_url_fkey', 'tweet', 'tweet_media', ['media_url'], ['id'])
    op.drop_column('tweet', 'media_id')
    # ### end Alembic commands ###
