"""media_id_relationship

Revision ID: be7a5dcc7972
Revises: b3b9daaf1741
Create Date: 2019-05-19 14:26:25.233267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7a5dcc7972'
down_revision = 'b3b9daaf1741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tweet_media_id_fkey', 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'media_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tweet_media_id_fkey', 'tweet', 'tweet_media', ['media_id'], ['id'])
    # ### end Alembic commands ###
