"""media_id_relationship_rev

Revision ID: c112c1cf87da
Revises: be7a5dcc7972
Create Date: 2019-05-19 14:37:53.918065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c112c1cf87da'
down_revision = 'be7a5dcc7972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
