"""media_id_relationship_rev2

Revision ID: c82fa9fa7966
Revises: c112c1cf87da
Create Date: 2019-05-19 14:39:05.375740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82fa9fa7966'
down_revision = 'c112c1cf87da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
