"""'multiple_foreign'

Revision ID: 051625ca9011
Revises: 62d7d88dc119
Create Date: 2019-05-30 20:55:08.612025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051625ca9011'
down_revision = '62d7d88dc119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
