"""'twitter_account_user_id'

Revision ID: 10fbb7bebd9b
Revises: 1c4312a478a0
Create Date: 2019-05-28 13:56:06.040260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fbb7bebd9b'
down_revision = '1c4312a478a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_account', sa.Column('account_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_account', 'account_user_id')
    # ### end Alembic commands ###
