"""'user_new_relationship'

Revision ID: 1c4312a478a0
Revises: 5f61fabf04af
Create Date: 2019-05-28 12:41:47.098120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4312a478a0'
down_revision = '5f61fabf04af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_twitter_account_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'twitter_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_twitter_account_id_fkey', 'user', 'twitter_account', ['twitter_account_id'], ['id'])
    # ### end Alembic commands ###
