"""'debug'

Revision ID: 3b342d7c8ea3
Revises: c7d331a12e41
Create Date: 2019-05-29 20:41:53.899355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b342d7c8ea3'
down_revision = 'c7d331a12e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
