"""'user_new_relationship'

Revision ID: 5f61fabf04af
Revises: ea94f6e2c472
Create Date: 2019-05-28 12:40:45.362456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f61fabf04af'
down_revision = 'ea94f6e2c472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
