"""'add_twitter_account_related'

Revision ID: 62d7d88dc119
Revises: db3e66925f5a
Create Date: 2019-05-30 20:44:00.454469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d7d88dc119'
down_revision = 'db3e66925f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('twitter_account_linked', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'server', 'twitter_account', ['twitter_account_linked'], ['id'])
    op.add_column('twitter_account', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('user_twitter_account', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'twitter_account', ['user_twitter_account'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_twitter_account')
    op.drop_column('twitter_account', 'notification_enabled')
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.drop_column('server', 'twitter_account_linked')
    # ### end Alembic commands ###
