"""'twitch_id'

Revision ID: 67f7831c9eb8
Revises: fadf99d4515e
Create Date: 2019-05-28 21:28:09.055777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f7831c9eb8'
down_revision = 'fadf99d4515e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
