"""'twitch_tokens'

Revision ID: 689620a9c5a8
Revises: deea79bd1368
Create Date: 2019-05-28 20:49:04.078389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689620a9c5a8'
down_revision = 'deea79bd1368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_account', sa.Column('twitch_access_token', sa.String(), nullable=True))
    op.add_column('twitch_account', sa.Column('twitch_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitch_account', 'twitch_refresh_token')
    op.drop_column('twitch_account', 'twitch_access_token')
    # ### end Alembic commands ###
