"""'user_model_twitter_account'

Revision ID: 797dd0f0d6b1
Revises: b50fe7dfdbcf
Create Date: 2019-05-27 22:22:28.905084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797dd0f0d6b1'
down_revision = 'b50fe7dfdbcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
