"""'twitch_user_id''

Revision ID: 7f1bc930532d
Revises: f571e057462a
Create Date: 2019-05-28 21:54:34.269256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1bc930532d'
down_revision = 'f571e057462a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_account', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'twitch_account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'twitch_account', type_='foreignkey')
    op.drop_column('twitch_account', 'user_id')
    # ### end Alembic commands ###
