"""'init'

Revision ID: b50fe7dfdbcf
Revises: 
Create Date: 2019-05-27 22:21:33.472143

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'b50fe7dfdbcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitch_account',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('twitch_name', sa.String(), nullable=True),
                    sa.Column('twitch_url', sqlalchemy_utils.types.url.URLType(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('discord_user_id', sa.String(), nullable=True),
                    sa.Column('dark_theme_enabled',
                              sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('server',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('server_id', sa.String(), nullable=True),
                    sa.Column('server_name', sa.String(), nullable=True),
                    sa.Column('discord_admin_id', sa.String(), nullable=True),
                    sa.Column('admin_id', sa.Integer(), nullable=True),
                    sa.Column('admin_name', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('twitter_account',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('twitter_name', sa.String(), nullable=True),
                    sa.Column('access_token', sa.String(), nullable=True),
                    sa.Column('access_secret', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tweet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tweet_content', sa.String(
                        length=280), nullable=True),
                    sa.Column('tweet_url', sqlalchemy_utils.types.url.URLType(),
                              nullable=True),
                    sa.Column('tweet_date', sa.DateTime(), nullable=True),
                    sa.Column('twitter_account_id',
                              sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['twitter_account_id'], [
                        'twitter_account.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tweet_media',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'media_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
                    sa.Column('tweet_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_media')
    op.drop_table('tweet')
    op.drop_table('twitter_account')
    op.drop_table('server')
    op.drop_table('user')
    op.drop_table('twitch_account')
    # ### end Alembic commands ###
