"""twitch_notifs

Revision ID: c7d331a12e41
Revises: 7f1bc930532d
Create Date: 2019-05-29 19:13:32.952432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d331a12e41'
down_revision = '7f1bc930532d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
