"""'modify_name'

Revision ID: dce1e1ede238
Revises: 3b342d7c8ea3
Create Date: 2019-05-30 16:04:42.692810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce1e1ede238'
down_revision = '3b342d7c8ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_account', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('twitch_account', sa.Column('refresh_token', sa.String(), nullable=True))
    op.drop_column('twitch_account', 'twitch_access_token')
    op.drop_column('twitch_account', 'twitch_refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_account', sa.Column('twitch_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('twitch_account', sa.Column('twitch_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('twitch_account', 'refresh_token')
    op.drop_column('twitch_account', 'access_token')
    # ### end Alembic commands ###
