"""'user_model_twitter_account'

Revision ID: ea94f6e2c472
Revises: 797dd0f0d6b1
Create Date: 2019-05-27 22:26:01.659337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea94f6e2c472'
down_revision = '797dd0f0d6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'twitter_account', ['twitter_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'twitter_account_id')
    # ### end Alembic commands ###
