"""'twitch_user_relationship''

Revision ID: f571e057462a
Revises: 67f7831c9eb8
Create Date: 2019-05-28 21:42:55.768329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f571e057462a'
down_revision = '67f7831c9eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
