"""'twitch_id'

Revision ID: fadf99d4515e
Revises: 689620a9c5a8
Create Date: 2019-05-28 21:26:33.716593

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'fadf99d4515e'
down_revision = '689620a9c5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_account', sa.Column(
        'twitch_id', sqlalchemy_utils.types.url.URLType(), nullable=True))
    op.drop_column('twitch_account', 'twitch_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_account', sa.Column(
        'twitch_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('twitch_account', 'twitch_id')
    # ### end Alembic commands ###
